version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/student

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  seed:
    build: .
    depends_on:
      - mongo
    command: ["node", "data.js"]

  web:
    build: ../web
    ports:
      - "8090:80"
    depends_on:
      - app
    environment:
      - API_URL=http://app:3001/api/students

volumes:
  mongo-data: