apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
  - name: mongo
    port: {{.Values.mongo.port }}
    targetPort: {{.Values.mongo.port }}
    nodePort: {{.Values.mongo.nodePort }}
  type: NodePort