apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
  - name: http
    port: {{.Values.api.port }}
    targetPort: {{.Values.api.port }}
    nodePort: {{.Values.api.nodePort }}
  type: NodePort