apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: {{.Values.web.image }}
        ports:
        - containerPort: {{.Values.web.port }}
        nodePort: {{.Values.web.nodePort }}
        environment:
        - name: API_URL
          value: {{.Values.web.apiUrl }}