apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web
  ports:
  - name: http
    port: {{.Values.web.port }}
    targetPort: {{.Values.web.port }}
    nodePort: {{.Values.web.nodePort }}
  type: NodePort